spring.application.name=fishfeeder
server.port=8080

# API KEY DUY NH?T CHO T?T C? ESP32
device.api-key=fish-secret-123

# Th?i gian coi thi?t b? là offline n?u không g?i d? li?u
device.offline-timeout=10000